# Generated by Django 5.1 on 2024-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='static/submitted')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'card entries',
                'ordering': ['-submit_date'],
            },
        ),
    ]
