# Generated by Django 5.1 on 2024-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='project')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'project',
                'ordering': ['-submit_date'],
            },
        ),
        migrations.AlterField(
            model_name='gallery',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
