# Generated by Django 5.1 on 2024-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project_alter_gallery_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardentry',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
