# Generated by Django 5.1 on 2024-08-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_cardentry_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardentry',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/explore/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/gallery/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/project'),
        ),
    ]
